name: Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: python:3.10.6-slim-bullseye
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: poetry install
    - name: Test with pytest
      run: pytest
